### PR TITLE
Use Terser's `passes` option

### PR DESCRIPTION
**Pull request by guilhermesimoes**
https://terser.org/docs/options/#compress-options

`2` is optimal in terms of balancing minification time and size.
`99` is optimal in terms of minification size. Terser won't ever do 99 runs, it simply stops after a pass doesn't further reduce the size.

### CODE REVIEW

**Comment by privatenumber** [comment]
> 2 is optimal in terms of minification time.

Where does it say this?

The docs you linked says the opposite:

> passes (default: 1) -- The maximum number of times to run compress. In some cases more than one pass leads to further compressed code. Keep in mind more passes will take more time.

I think this is an unfair comparison as other minifiers are doing a single pass. Not to mention, I imagine it will slow down Terser dramatically.

**Comment by guilhermesimoes** [comment]
> 2 is optimal in terms of minification time.

I meant optimal in terms of minification time AND bundle size.

> If Terser's performance actually keeps improving with more runs, that sounds like suboptimal performance & design in Terser.

That seems fairly judgemental from a repository that should be neutral 🤔

> I think this is an unfair comparison as other minifiers are doing a single pass.

Do other minifiers support multiple passes? To my eyes it seems unfair not to measure what the tool can actually accomplish.

Perhaps it would fairer if there were two Terser results: `Terser (default)` and `Terser (passes: 2)`? 🤔

**Comment by privatenumber** [comment]
Result: https://github.com/privatenumber/minification-benchmarks/tree/patch-1

This basically slows down Terser with negligible improvements.

I don't think the average user would care to run Terser twice on their code so I'm closing this.

Fun experiment though.

**Comment by guilhermesimoes** [comment]
It achieved better minification on all bencharmks and on at least 2 benchmarks it surpassed `swc`. If paired with https://github.com/privatenumber/minification-benchmarks/pull/443 it should surpass `swc` in even more benchmarks.

> I don't think the average user would care to run Terser twice on their code so I'm closing this.

Presenting the results and letting the "average user" decide would make more sense, no?

**Comment by privatenumber** [comment]
For the ones it made a difference (moment & lodash), there wasn't even a 1% improvement (`40 B` & `50 B` respectively). If you look at how much the time went up, the cost is definitely not worth a couple of bytes.

> Presenting the results and letting the "average user" decide would make more sense, no?

To an extent. Sure, I can show how every configuration of each minifier affects the results. But eventually I have to draw the line or I compromise the readability of the benchmarks with uninsightful data.

With terser, I already give it the benefit of demonstrating two different configurations. I'm not going to add another one just to show a less than 1% improvement for minification when the area that needs more competition is clearly speed.

However, keep in mind this is open source. I don't need to do this but you can. Or even better, Terser can. I also imagine that people that set their minds on Terser would simply research how the different configurations affect their own build, as that's what matters most. These benchmarks are just a starting point to pick the minifier.

**Pull request closed without merging**
