### PR TITLE
More minification for esbuild

### PR DESCRIPTION
**Pull request by mischnic**
With the previous esbuild options, top-level variables weren't renamed. So 

```js
var somevariable = 2;
function f(){
    return somevariable;
}
console.log(f())
```
was minified to
```js
var somevariable=2;function f(){return somevariable}console.log(f());
```

With the added options, the output is
```js
var o=2;function e(){return o}console.log(e());
```

### CODE REVIEW

**Comment by privatenumber** [comment]
Thanks @mischnic 

Do you mind fixing the linting errors preventing the CI?

**Comment by mischnic** [comment]
> Do you mind fixing the linting errors preventing the CI?

Done

**Comment by privatenumber** [comment]
Based on [the docs](https://esbuild.github.io/api/#tree-shaking), it seems the `format: 'esm'` isn't necessary. It's just that it enables tree shaking by default, but the tree shaking option can be used to force-enable it. Can you remove it?

> By default, tree shaking is only enabled either when bundling is enabled or when the output format is set to iife, otherwise tree shaking is disabled. You can force-enable tree shaking by setting it to true:

I also made [this copy of your branch](https://github.com/privatenumber/minification-benchmarks/pull/43) since the GitHub Action doesn't work on forks, but enabling tree- shaking doesn't seem to yield any differences. Haven't checked but possibly because the distribution files are wrapped by UMD wrapper or something so there aren't any top-level variables. And maybe if there are, there aren't any unused ones because these are well written libraries that don't ship unused code.

Happy to merge this PR after `format` is removed though.

**Comment by mischnic** [comment]
> Haven't checked but possibly because the distribution files are wrapped by UMD wrapper or something so there aren't any top-level variables

You're right. All of them are wrapped in an IIFE, except for `vue/dist/vue.runtime.common.dev.js` which is a regular CJS module.

Without this change, the minified Vue bundle size is 95061 bytes. With this change, it's 79177.

> it seems the format: 'esm' isn't necessary

For the code sample in the original post, adding `treeShaking: true` doesn't make a difference. I had to add some format (`"cjs"` or `"esm"`) as well:
```js
const { transform } = require("esbuild");

(async () => {
	let { code, map } = await transform(`
var somevariable = 2;
function f(){
    return somevariable;
}
console.log(f())
`, {
		minify: true,
		treeShaking: true,
		format: "esm", // try commenting this out
	});
	console.log(code);
})();
```

**Comment by privatenumber** [comment]
It's working expectedly.

Note:
- When you toggle `format: 'esm'`, the difference in output isn't a result of tree-shaking but just plain minification (variable name mangling). (Try disabling `minify: true`, or comparing the output carefully to identify what code was tree-shaken.)
- Your input code actually has nothing to tree-shake because everything is used. Try using the input code from the docs: https://esbuild.github.io/api/#tree-shaking

The reason why it doesn't mangle the variable name without `format: 'esm'` is because by default, it assumes that it's not a module and therefore those variables are necessary to be access in the global scope (aka `window.somevariable = 2`).

**Pull request merged**
