### PR TITLE
chore: added tests for artifacts

### PR DESCRIPTION
**Pull request by privatenumber**
Runs the resulting minified code to verify it runs.

Partially addresses https://github.com/privatenumber/minification-benchmarks/issues/14

@kzc Thank you for your help with this. I'd like to credit you in some way for your contributions. Would it be ok to add an empty commit with your email so you show up in the contributors list (I think)?

### CODE REVIEW

**Comment by privatenumber** [comment]
Moving forward with this.

@kzc Happy to follow up with a commit that credits you if you'd like. Just let me know!

**Comment by kzc** [comment]
I'm glad the benchmark was updated to exclude non-working bundles - no need for attribution.

This README section still seems to be out of date, as all of the google-closure-compiler.advanced bundles failed verification:

> UglifyJS takes first place for minification performance by winning 9 out of 11 races. When short, it only loses to Google Closure Compiler by less than 9 kB! Impressively, it's still written in ES5 but can handle ES6 up to ES2020.

**Comment by privatenumber** [comment]
👍

Running this right now since it might fix it: https://github.com/privatenumber/minification-benchmarks/pull/19

Will follow up with a readme update. Thanks!

**Comment by kzc** [comment]
`jscomp_off: *` just disables warnings being treated like errors - it doesn't fix the bundles where the API properties have been incorrectly mangled.

**Comment by privatenumber** [comment]
Ah yeah you're right. No improvements in the [result](https://github.com/privatenumber/minification-benchmarks/tree/google-closure-compiler-advanced-jscomp_off).

Will follow up with readme updates.

Thanks again.

**Comment by kzc** [comment]
Consider ordering each test result by minified gzip size (Minzipped in your chart) since over the wire size is what matters at the end of the day. This would give terser a couple of test wins. Also probably worth mentioning in the final summary that terser typically produces minified gzip sizes within a percent of uglify-js, and runs twice as fast.

**Pull request merged**
