### PR TITLE
feat: add "typescript" as artifact

### PR DESCRIPTION
**Pull request by g-plane**
TypeScript compiler is about 10 MiB, so I think it can be artifact for benchmark.

### CODE REVIEW

**Comment by g-plane** [comment]
Oh, I haven't noticed this fact. But, would it be a challenge for minifiers?

**Comment by g-plane** [comment]
Will this PR be merged or not?

**Comment by privatenumber** [comment]
Thanks for the reminder.

I planned on it, but a Renovate PR came in and there were conflicts that I procrastinated on resolving. Will merge this via https://github.com/privatenumber/minification-benchmarks/pull/103

**Comment by privatenumber** [comment]
Merged. Thanks for your patience @g-plane

**Pull request closed without merging**
