### PR TITLE
chore: fix trophy placement in smallest size column

### PR DESCRIPTION
**Pull request by privatenumber**

### CODE REVIEW

**Comment by kzc** [comment]
No trophy in uncompressed `Minified size` column?

https://github.com/privatenumber/minification-benchmarks/pull/29/commits/3642be279a64037daa185fd72f5d1aa0d899adc3?short_path=5a831ea#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15

**Comment by privatenumber** [comment]
Wrong property 🤦‍♂️

**Comment by kzc** [comment]
One last request - could you use 2 or 3 decimals of precision for byte-size? The larger bundles only show values like `1.2 MB` which are too coarse grained to differentiate sizes. Case in point, these values are nearly a percent different in size but appear the same:

```
$ node -p 'require("byte-size")(1234567)'
ByteSize { value: '1.2', unit: 'MB', long: 'megabytes' }

$ node -p 'require("byte-size")(1249999)'
ByteSize { value: '1.2', unit: 'MB', long: 'megabytes' }
```

with 2 decimals:
```
$ node -p 'require("byte-size")(1234567, {precision: 2})'
ByteSize { value: '1.23', unit: 'MB', long: 'megabytes' }

$ node -p 'require("byte-size")(1249999, {precision: 2})'
ByteSize { value: '1.25', unit: 'MB', long: 'megabytes' }
```

**Comment by privatenumber** [comment]
Sure, will address in a follow up PR

**Pull request merged**
